### ISSUE TITLE
Support working with vim sessions

### ISSUE THREAD

**Issue by dtrckd** [dhruvasagar/vim-zoom#32] opened 2022-12-23 14:38 UTC
vim-zoom seems to loose some tabs state when working with session extension;
I have tried to create sessions with multiple tab opened with the following plugins: 
- https://github.com/mhinz/vim-startify
- https://github.com/romgrk/vim-session

Reproduce:
- open a vim window with two tabs open, split a tab, zoom in a file, then unzoom.
- save the session (:SSave // :SaveSession)
- close vim, and reopen the saved session.

In both cases, the session will have lost the tabs, except the one from which you saved the session.

Is it a vim setting that could get lost when unzooming ?

**Comment by dhruvasagar** [comment] 2022-12-30 03:05
I looked at the code and I don't see anything that should cause this. As long as you save your session after zooming it should be good.
I'll try to reproduce this and see if this is something caused by vim-zoom

**Comment by dhruvasagar** [comment] 2023-01-19 14:12
@dtrckd I haven't really been able to reproduce this. Are you still facing this issue ? What platform are you on ?

**Comment by dtrckd** [comment] 2023-01-19 14:37
I am running on debian 11.6.

At the time of posting the issue, I ran the POC with vim and vim.nox. Meanwhile I moved to neovim (0.8.2), and the issue doesn't seem to exist anymore there...

thanks for investigating!

**Comment by dhruvasagar** [comment] 2023-01-19 14:39
Np, i'll close this issue for now. We can revisit in future if it appears again.

**Closed as completed by dhruvasagar** 2023-01-19 14:39 UTC
